### PR TITLE
Fix favicon img

### PR DESCRIPTION
**Pull request by samsonasik**
|    Q          |   A
|-------------- | ------
| Bugfix        | yes

### Description

Previously, it still uses zf favicon, updated to use laminas favicon.

### CODE REVIEW

**Comment by froschdesign** [comment]
The same here: outdated logo.

@weierophinney 
We can use the logos with the "M" and coloured background here. What do you think?

**Comment by weierophinney** [comment]
@froschdesign That sounds good - should I merge this one, or are you suggesting an alternative?

**Comment by froschdesign** [comment]
@weierophinney 
I gave you some SVG files on Slack.

**Comment by weierophinney** [comment]
> I gave you some SVG files on Slack.

I'd forgotten! I'll update here, and start updating the orgs.

**Comment by samsonasik** [comment]
seems already fixed. closing.

**Pull request closed without merging**
